// <auto-generated />
using System;
using Bliss.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bliss.Shared.Migrations
{
    [DbContext(typeof(BlissContext))]
    [Migration("20220529094056_AddTables")]
    partial class AddTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("Bliss.Models.Cruise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveWaypoint")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cruises");
                });

            modelBuilder.Entity("Bliss.Models.WayPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Arrival")
                        .HasColumnType("TEXT");

                    b.Property<int>("CruiseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Departure")
                        .HasColumnType("TEXT");

                    b.Property<double>("EndLat")
                        .HasColumnType("REAL");

                    b.Property<double>("EndLng")
                        .HasColumnType("REAL");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<double>("StartLat")
                        .HasColumnType("REAL");

                    b.Property<double>("StartLng")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CruiseId");

                    b.ToTable("WayPoints");
                });

            modelBuilder.Entity("Bliss.Models.WayPoint", b =>
                {
                    b.HasOne("Bliss.Models.Cruise", null)
                        .WithMany("WayPoints")
                        .HasForeignKey("CruiseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bliss.Models.Cruise", b =>
                {
                    b.Navigation("WayPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
